[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
legacy = "3KMevqDU8As9FLQEqJQheLXUKAXoHZW5D2KfangLu3CY"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://api.devnet.solana.com"
# cluster = "mainnet"
# cluster = "https://divine-compatible-gas.solana-devnet.quiknode.pro/a87fea433fe4bef41c0b33281901aaad7d027214/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
